### ISSUE TITLE
17599 - Moroccan Jews - 9363 incorrectly assigned

### ISSUE THREAD

**Issue by dorshilton** [theglobaljukebox/cantometrics#104]
9363 performed by Moshe Vital, a Turkish hazzan. 
The correct URL https://folkways.si.edu/moshe-vital/cantorial-style-prayer-for-the-day-of-yom-kippur-turko-sephardic-version/islamica-world/music/track/smithsonian
Track info also assigns it to Turkey
Should be assigned to Turkish Jews, which doesn’t current exist

**Comment by stellasilbert** [comment]
Created Turkish Jews society and assigned this song. I located the society in Istanbul because that seemed to be where a lot of Jewish history in Turkey has been located, plus that was where glottolog coordinates for ladi1251 were located. Could not find any more specific info about the performer or the song to pinpoint a location. Istanbul is in European Turkey and might technically go under the Europe region, but I left it in Western Asia because the society as a whole could include Jews from other parts of Turkey. Geographic classification looks like this:

<google-sheets-html-origin><style type="text/css"></style>

Western Asia | Turkish Thrace | Marmara Reg | Istanbul | Turkish Jews
-- | -- | -- | -- | --
