### ISSUE TITLE
28986 - Yaqui

### ISSUE THREAD

**Issue by dorshilton** [theglobaljukebox/cantometrics#128]
898 is longer version of 164 - so 164 should be removed. The two are coded differently, so could be worth recoding the track. Spelling for recorder surname is Yurchenko (though the album cover says Urchenko).

899 is recorder by Laura C. Boulton, as indicated in the album.

society centroid could be move closer to songs and EA and GeLaTo centroids. EA Yaqui is 28, -110.

**Comment by stellasilbert** [comment]
Looking into this-- audio for 898 actually seems to be incorrect. It shouldn't be the same song as 164. Coding and metadata are correct. Replaced with correct audio file.

Corrected spelling of Henrietta Yurchenko for song 164.

898 and 899 should both have recordist name as Laura Boulton. Correction implemented.

Recording location for 898 and 899 is indeed Tlaxcala, but the liner notes clarify that this is where Yaqui people have been displaced to due to being enrolled in the Mexican army, and emphasizes their connection to their homeland in Sonora. I am changing location name to "Yaqui Valley, Sonora, Mexico [Recorded in Tlaxcala, Mexico]" and moving lat-lons to Yaqui Valley.

Changed society centroid to lat-lon of all songs (27.36, -110.16), which is closer to EA centroid as well.
