### ISSUE TITLE
Suggest merging societies 28117 (Uttar Pradesh) and 12024 (Benares)?

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#165]
Reasoning: 
- Benares (Varanasi) is in Uttar Pradesh.
- Two songs currently assigned to 28117, Uttar Pradesh, are located in Varanasi (9918 and 9920).
- Three songs currently assigned to 12024, Benares, are have location names that don't correspond to Varanasi specifically. Songs 9901 and 9913 have location name "Uttar Pradesh, India," and song 752 has location "Mirzapur, Uttar Pradesh, India ."
- I assume the reason for the separation was to separate littoral/monastic songs from other folk songs. The "People" field for 12024 says "Hindu/ Buddhist Monastics." However, not all of the songs assigned to 12024 seem to be religious songs, and a couple songs assigned to 28117 _are_ religious songs.
- There is an EA match for Uttar Pradesh, but not for Benares.

So, I suggest assigning all songs to 28117, keeping the name Uttar Pradesh, and deleting society 12024. However, I will defer to @annalwood before doing so, in case there is a good reason not to do it.

**Comment by stellasilbert** [comment]
Ok, so Benares/monastic songs will be kept separate from Uttar Pradesh/folk songs. I have done the following:

1) Renamed 12024 "Varanasi Monastics"
2) Reassigned songs 1029, 752, 9901 and 9897 to 28117 (Uttar Pradesh) because they are folk songs.

**Comment by annalwood** [comment]
www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*


"Mirzapur could be a location. the others uttar pradesh unidentified
location?
