### ISSUE TITLE
What is the difference between society 27462 (Trinidad) and 27457 (Trinidad Creole)?

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#242]
I cannot find any indication of what the difference is between these two societies by looking at the society or song metadata. Both societies have language "Trinidadian Creole English," People "Trinidad & Tobago Creole," and all the same other metadata, except society location is slightly different. Looking at the songs, I don't see any pattern indicating why they would be assigned to two different societies. 50 songs are assigned to Trinidad Creole, and 7 songs to Trinidad. @annalwood, unless there is a reason for keeping them separate, I suggest merging these two societies.

**Comment by annalwood** [comment]
Change to one society.  Also do we still have Trinidadian spiritual?  That
should also be Trinidadian creole

There are a number of instances where a society or people seems to be split
in the GJB


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*
