### ISSUE TITLE
Impossible value

### ISSUE THREAD

**Issue by SamPassmore** [theglobaljukebox/cantometrics#26]
Hi Anna and Stella, 

I have found an impossible value in:

Line_1 - song_id 3862 - society_id 13102

Currently the value is 5264

Is there a way to check if this value has been input correctly? 

Sam

**Comment by stellasilbert** [comment]
It's not an impossible value, it is a quadruple coding of points, 4, 7, 10, and 12, as per the original coding sheet: https://www.loc.gov/resource/afc2004004.ms431701/?st=slideshow#slide-24

I suppose it is debatable whether or not a quadruple coding like that is appropriate in a given situation, but logically it is not impossible. However I think there are probably several multi-codings like this that were not defined in the codebook, because during the course of correcting the errors that John had identified, I found many other digitization errors that I corrected where values had been multi-coded on the original sheet but not digitally. This specific example was one of those.

**Comment by SamPassmore** [comment]
Ah ok. 

I had been told that the maximum number of codings in Cantometrics was 3, which I made a constraint in the tests to save time and why this comes up as an error. This is an easy fix then. 

This is the only multi-coding error I get so I don't think there are any other quarduple codings except for this one. 

Thanks for a quick response.
