### ISSUE TITLE
12563 - Bosnia

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#263]
Multiple issues here.

1. The society is called Bosnia and all songs are recorded in Bosnia. However, Bosnia is a multi-ethnic nation, and only one of the songs assigned to this society (song 351) is actually by ethnic Bosnians/Bosniaks, in Bosnian language. Song 352 is in Serbian, and Song 350 is in Croatian. Currently, the language assigned to the society is Serbian serb1264. I think it would make sense to leave song 351 assigned to Bosnia society, and update the language to Bosnian; then, reassign song 350 to Croatian society, and song 352 to Serbia society. 
2. Song 352 has incorrect audio and metadata. The correct song is called KAHARLI SAM, VEČERALA NISAM, and there are liner notes with info on Dropbox. Audio can be heard on Spotify [here](https://open.spotify.com/track/21eKV6RMVyjE5tW1zFYnSl?si=744ccbd41cff46b1), and I will try to track down an audio file or purchase one.
3. Society lat-lon is at the southwestern edge of Bosnia. Should probably be more central, where the recordings are. If reassigned as suggested in point 1, the remaining song assigned to Bosnia has lat-lon of 44.33, 17.27. That could be used as society lat-lon.

**Comment by stellasilbert** [comment]
@annalwood could I get your opinion on point 1? Should the songs be reassigned based on linguistic/ethnic group? Or kept together under Bosnia because they were all recorded there?

**Comment by annalwood** [comment]
If they're Croats or Serbs or others, reassign.  But people are
multilingual in this region, so is there any other basis for thinking they
may not be Bosnian?


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*

**Comment by stellasilbert** [comment]
Good question. The song sung in Croatian is described as being "from a Croatian enclave," so I would assume that performers are ethnic Croats. The song in Serbian doesn't have enough info to tell, so perhaps that one can be left assigned to Bosnia, and a note made in the metadata that it is sung in Serbian. I know the languages are all pretty similar too.

**Comment by annalwood** [comment]
So, they would be assigned to Croatia and Serbia respectively, with a note
about their being a C. enclave in Bosnia, and the recording location being
in Croatia...  What do you think about the recording location?


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*

**Comment by stellasilbert** [comment]
I think even if we reassign the song to the Croatian society, the location should stay in Bosnia, because Bosnia is a multiethnic nation that includes Croatians, and it was still Yugoslavia when the recordings were made. If it were Croatian immigrants being recorded in an unusual place, I would agree that location should be changed to Croatia, but it seems like the performers are in their homeland, which happens to be a Croatian enclave within Bosnia. Otherwise, totally agree with your suggestion and will definitely make a note.

**Comment by annalwood** [comment]
What I said was reassign to Croatian culture, and more briefly what you
said about Bosnia being multi ethnic.  Maybe call them Croatian Bosnians
located in Bosnia and People Croats?


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*

**Comment by annalwood** [comment]
I don't think that its that important but we have other enclaves elsewhere
so maybe yes.


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*
