### ISSUE TITLE
Incorrect values?

### ISSUE THREAD

**Issue by SamPassmore** [theglobaljukebox/cantometrics#27]
Hi @stellasilbert 

Could you double check some values for me and whether they are valid?

Song ID 3981 - Line 14 - Value 8376
Song ID 831    - Line 25 - Value 1028
Song ID 832   - Line 25 - Value 1028

These come up as errors in the tests, but maybe the tests are overlooking something.

**Comment by SamPassmore** [comment]
I think songs 831 & 832 line 25 have been errors before in  #18 
So, maybe these are correct but the test is wrong. Would be good to iron out why.

**Comment by stellasilbert** [comment]
Hi Sam,

Song ID 3981 - Line 14 was a typo, it was supposed to be 8736 (triple code of points 5, 9, and 13). My bad! Fixed it on the google sheet.

The other two, the values of 1028 on line 25 of 831 & 832, which came up before, are indeed impossible values. They hadn't been resolved because I was trying to sort out an issue with those two codings and a few others not matching the original hard copy coding sheets. However, the audio matches the codings that we have, so Anna agreed it would be fine to correct those values based on listening to the audio for now, and to deal with the larger problem of them being inconsistent with the paper files later. I've corrected them both to 1040 (double code of points 10 and 4), which seems to be what was meant, based on the audio.
