### ISSUE TITLE
Society Checking - 24707 - Sakalava

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#88]
1. Lat-lon correction
Song 1620: Tape notes name location as "Doany." Current location in metadata is Doany Village, Tananarive, Madagascar, and lat-lon is -18.87, 47.5 (in Antanarivo aka Tananarive). However, coordinates for Doany are -14.37, 49.52-- not in Tananarive. This actually puts it farther away from the other Sakalava songs we have, but tape notes list the culture as Sakalava, and Doany is not far from the northernmost part of Sakalava territory.

2. Society match notes

All songs except for 1620 and 2176 seemed to be in Sakalava territory based on wikipedia, so I didn't check those. Assuming they are all correctly assigned to Sakalava.

Tape notes for 2176 identify it as a Masikoro song. The Masikoro are a subgroup of Sakalava people; however, so are the Vezo and Mikea people, and we have assigned separate society ids for those groups. So perhaps we should do the same for Masikoro? @annalwood What do you think?

See note above regarding 1620. 

Suggest changing society lat-lon to average song lat-lon (-22.12, 44.22). This brings it closer to D-PLACE and Glottolog lat-lon.

**Comment by stellasilbert** [comment]
Updated song and society lat-lons as suggested above.

@annalwood , please advise on the following issue: Tape notes for 2176 (currently assigned to Sakalava) identify it as a Masikoro song. The Masikoro are a subgroup of Sakalava people; however, so are the Vezo and Mikea people, and we have assigned separate society ids for those groups. So perhaps we should do the same for Masikoro (i.e. create a new Masikoro society and assign song 2176 to it)?

**Comment by annalwood** [comment]
Stella I looked very carefully at madagascar at one point.  some of the
groups are spread around the island.  I don't remember which.  They are not
concentrated in one spot.  The 'subgroups' should all be separate, but
people should be sakalava.  I seem to recall that Sakalava was big
container vateghory.


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*

**Comment by stellasilbert** [comment]
Ok great. Created Masikoro society and reassigned that song to it.
